use eyre::Result;
pub use span_metrics::TimeSpanLifetime;
use tracing_subscriber::{
    filter::{filter_fn, LevelFilter},
    fmt as tracing_fmt,
    prelude::*,
    EnvFilter,
};

use crate::{ CoreMetrics};

/// Configure a `tracing_subscriber::fmt` Layer outputting to stdout
pub mod fmt;

mod span_metrics;

/// Logging level. A "higher level" means more will be logged.
#[derive(Default, Debug, Clone, Copy, serde::Deserialize, PartialOrd, Ord, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub enum Level {
    /// Off
    Off = 0,
    /// Error
    Error = 1,
    /// Warn
    Warn = 2,
    /// Debug
    Debug = 4,
    /// Trace
    Trace = 5,
    /// Trace + Additional logs from dependencies
    DependencyTrace = 6,
    /// Info
    #[serde(other)]
    #[default]
    Info = 3,
}

impl From<Level> for LevelFilter {
    fn from(level: Level) -> LevelFilter {
        match level {
            Level::Off => LevelFilter::OFF,
            Level::Error => LevelFilter::ERROR,
            Level::Warn => LevelFilter::WARN,
            Level::Debug => LevelFilter::DEBUG,
            Level::Trace | Level::DependencyTrace => LevelFilter::TRACE,
            Level::Info => LevelFilter::INFO,
        }
    }
}

/// Configuration for the tracing subscribers used by Hyperlane agents
#[derive(Debug, Clone, Default, serde::Deserialize)]
pub struct TracingConfig {
}

impl TracingConfig {
    /// Attempt to instantiate and register a tracing subscriber setup from
    /// settings.
    pub fn start_tracing(&self, _metrics: &CoreMetrics) -> Result<console_subscriber::Server> {
        let (_, tokio_server) = console_subscriber::ConsoleLayer::new();

        // Define a filter function to exclude spans generated by #[instrument]
        let span_filter = filter_fn(|metadata| {
            // filter spans and returns from spans
            if metadata.is_event() && !metadata.fields().iter().any(|f| f.name() == "return") {
                return true;
            }

            // Allow logging of filtered spans if they are WARN or higher
            return metadata.level() <= &LevelFilter::WARN;
        });

        let log_format = tracing_fmt::format::Format::default()
            .compact()
            .with_target(false)
            .with_level(true);
        let subscriber = tracing_subscriber::Registry::default().with(
            tracing_fmt::layer()
                .event_format(log_format)
                .with_filter(EnvFilter::from_default_env())
                .with_filter(span_filter),
        );

        subscriber.try_init()?;
        Ok(tokio_server)
    }
}
